### ISSUE TITLE
TLS 1.2

### ISSUE THREAD

**Issue by jchannon** [JeremySkinner/SagePayMvc#24]
I've received the attached message from SagePay.  I'm pretty sure SagePayMVC uses https in its communications but just wanted to check there's nothing to worry about and it will continue functioning ok.

Thanks
![screen shot 2018-01-29 at 16 55 02](https://user-images.githubusercontent.com/105126/35522847-5559c708-0515-11e8-8380-b71a1a7640dc.png)

**Comment by JeremySkinner** [comment]
Yes it should be fine, no changes should be necessary inside SagePayMvc itself, but if you’re running on an older version of .net (prior to 4.6 I believe) TLS 1.2 is not the default for requests so you’ll have to explicitly enable that by setting ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12; (in the app startup routine)

**Comment by jchannon** [comment]
Ah thanks for the pointer. The app in question os on MVC4 and targeting .Net4 `<compilation debug="true" targetFramework="4.0">` I believe

**Comment by jchannon** [comment]
Which means SSL3 or TLS1.0 are the only options 😄

**Comment by JeremySkinner** [comment]
On 4.0 I don’t think that enum value is even present so you’d have to cast an integer instead: ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072;

**Comment by JeremySkinner** [comment]
Yeah that had the same effect even though the enum options are missing (as it’s actuallg an OS feature). If you’re on old windows version (2008 R2) then you’ll need to enable it with a registry change, and if you’re on an even older version (2008) you’ll need to install a hot fix from MS.

**Comment by jchannon** [comment]
OK this is fun. It's on a shared hosting package with Windows 2008 R2 and
no way to run it on .Net 4.6 for example.

Assuming you can run MVC4 on 4.6 I"ll see if I can get the hosting company
to transfer it to a server that can handle that :)

**Comment by JeremySkinner** [comment]
If not then you should be able to still run fine on 4.0 using the version of that code with the integer cast so long as the host is willing to enable the appropriate registry flag: https://support.quovadisglobal.com/kb/a433/how-to-enable-tls-1_2-on-windows-server-2008-r2.aspx

**Comment by jchannon** [comment]
Thanks, hosting provider had 4.6.2 installed so could retarget it and assign ServicePointManager.SecurityProtocol = Tls12

Thanks for the great pointers, much appreciated
