### ISSUE TITLE
Incorrect test results?

### ISSUE THREAD

**Issue by jchannon** [JeremySkinner/SagePayMvc#28]
I'm looking at the tests here https://github.com/JeremySkinner/SagePayMvc/blob/master/src/SagePayMvc.Tests/DefaultUrlResolverTester.cs#L58 and the way the `RouteValueDictionary` works I think it converts unnamed keys/non mvc route keys to querystring so the result should be `"http://foo.com/PaymentResponse/Success?vendorTxCode=foo"` not `http://foo.com/PaymentResponse/Success/foo` but I'm not sure how this test is passing?

**Comment by JeremySkinner** [comment]
The test is correct - the DefaultUrlResolver uses the route table to generate the URL, and that route structure is defined at the top of that file https://github.com/JeremySkinner/SagePayMvc/blob/d1d72e85ba74aff59718c864be7c3a75a30d71c2/src/SagePayMvc.Tests/DefaultUrlResolverTester.cs#L38

In that route, `vendorTxCode` is defined as an explicitly named route parameter.

**Comment by jchannon** [comment]
Ahhhhh! I missed that completely, thanks!
